### ISSUE TITLE
Centos 7  -> myql_client_installation ->  Chef::Exceptions::Package

### ISSUE THREAD

**Issue by rschmidtz** [chef-cookbooks/mysql#446]
### Cookbook version

8.0.1
### Chef-client version

12.11.18
### Platform Details

Centos 7.2
### Scenario:

Attempt to install MySQL Server and Client using Kitchen and Vagrant.

### Steps to Reproduce:

attributes
-------------

normal_unless['customers']['database']['root_password'] = random_password
normal_unless['customers']['database']['admin_password'] = random_password

metadata
-------------
depends 'mysql', '~> 8.0.1'

recipe
---------
mysql_client 'default' do
  action :create
end

mysql_service 'default' do
  initial_root_password node['customers']['database']['root_password']
  action [:create, :start]
end

Run Kitchen
-----------------

kitchen converge

### Expected Result:

Install should complete successfully and mysql server should be running.

### Actual Result:

Running handlers:
       [2016-08-04T14:50:47+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-08-04T14:50:47+00:00] ERROR: Exception handlers complete
       Chef Client failed. 91 resources updated in 06 minutes 14 seconds
       [2016-08-04T14:50:47+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-08-04T14:50:47+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-08-04T14:50:47+00:00] ERROR: mysql_client_installation_package[default] (awesome_customers::database line 6) had an error: Chef::Exceptions::Package: yum_package[mysql-community-client] (/tmp/kitchen/cache/cookbooks/mysql/libraries/mysql_client_installation_package.rb line 18) had an error: Chef::Exceptions::Package: No candidate version available for mysql-community-client
       [2016-08-04T14:51:48+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by propertydev** [comment]
I'm having this problem too when trying to install it via vagrant, berksfile & chef.

**Comment by whizz** [comment]
This unfortunately also breaks php cookbook source recipe, because it tries to install the client and on CentOS 7 the package is not available. You probably need to add the MySQL repository.

**Comment by someara** [comment]
Fixed up in 8.0.2

**Comment by whizz** [comment]
It still fails for me on CentOS 7.2, no change.

**Comment by darrenhaken** [comment]
I am also facing this issue - did it get fixed?

**Comment by saidmasoud** [comment]
@someara : this is still failing. I tried cookbook version 8.5 with no luck. Any ideas?
